apiVersion: v1
kind: Pod
metadata:
  namespace: yuyang
  name: pod-light-year-admin-template
spec:
  containers:
    - name: light-year-admin-template
      image: harbor.labworlds.cc/light-year-admin-template/master:08111856-yuyang
      resources:
        limits:
          cpu: 0.2
          memory: 256Mi
        requests:
          cpu: 0.1
          memory: 128Mi
      ports: 
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        exec:
          command:
          - sh
          - -c
          - ps aux | grep nginx || netstat -lput | grep 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3
      volumeMounts:
      - name: volume-configmap-app-file
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      - name: volume-secret-admin-yuyang-com
        mountPath: /etc/nginx/ssl/admin.yuyang.com/certificate.crt
        subPath: tls.crt
      - name: volume-secret-admin-yuyang-com
        mountPath: /etc/nginx/ssl/admin.yuyang.com/private.key
        subPath: tls.key
  volumes:
    - name: volume-configmap-app-file
      configMap:
        name: configmap-app-file
    - name: volume-secret-admin-yuyang-com
      secret:
        secretName: secret-admin-yuyang-com
  imagePullSecrets:
    - name: secret-harbor-login