apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-yuyang-redis-exist
spec:
  capacity:
    storage: 64Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/yuyang-redis-exist-pvc
    server: 192.168.110.168
