apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-yuyang-redis
  namespace: yuyang
  labels:
    app: pvc-yuyang-redis
spec:
  # storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Mi