apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-admin3-ui
  namespace: yuyang
  labels:
    app:  deployment-admin3-ui
spec:
  selector:
    matchLabels:
      app: deployment-admin3-ui
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  deployment-admin3-ui
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  deployment-admin3-ui
        image:  harbor.labworlds.cc/admin3-ui/master:08131833-yuyang
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  80
          name:  http
        volumeMounts:
        - name: volume-configmap-admin-ui
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        # - name: volume-configmap-admin-ui
        #   mountPath: /app/.env
        #   subPath: env
      volumes:
        - name: volume-configmap-admin-ui
          configMap:
            name: configmap-admin3-ui
      restartPolicy: Always
      imagePullSecrets:
        - name: secret-harbor-login
      # nodeSelector:
      #   kubernetes.io/hostname: k8s-node-yy-137