apiVersion: v1
kind: Service
metadata:
  name: "headless-redis-not-exist-pvc"
  namespace: yuyang
spec:
  selector:
    app: "pod-redis-not-exist-pvc"
  clusterIP: None
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379