apiVersion: v1
kind: Service
metadata:
  name: service-admin3-ui
  namespace: yuyang
spec:
  selector:
    app: deployment-admin3-ui
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
