apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-admin3-server
  namespace: yuyang
  labels:
    app:  deployment-admin3-server
spec:
  selector:
    matchLabels:
      app: pod-admin3-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  pod-admin3-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: pod-admin3-server
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: pod-admin3-ui
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name:  pod-admin3-server
        image:  harbor.labworlds.cc/admin3-server/master:08121853-yuyang
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /admin3/actuator/health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  8080
        volumeMounts:
        - name: volume-configmap-admin3-server
          mountPath: /app/application.yml
          subPath: application.yaml
      volumes:
        - name: volume-configmap-admin3-server
          configMap:
            name: configmap-admin3-ui-server
      restartPolicy: Always
      imagePullSecrets:
        - name: secret-harbor-login
      nodeSelector:
        kubernetes.io/hostname: k8s-node-yy-137