apiVersion: v1
kind: Service
metadata:
  name: servcie-admin3-server
  namespace: yuyang
spec:
  selector:
    app: deployment-admin3-server
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080