apiVersion: v1
kind: Secret
metadata:
  name: secret-harbor-login
  namespace: yuyang
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"yydsops-harbor.labworlds.cc":{"username":"admin","password":"admin123"}}}'